import type { Datetime, Did } from "@atcute/lexicons";
import pg from "pg";
import type { SignedLabel } from "../util/types.js";
import type { LabelQuery, LabelStore, StoredLabel } from "./LabelStore.js";

/** The subset of a `pg` query result used by the store. */
interface PgResult {
	rows: Array<Record<string, unknown>>;
}

/** Anything that can run a parameterized query, such as a `pg` Pool or PoolClient. */
export interface PgQueryable {
	query(text: string, values?: Array<unknown>): Promise<PgResult>;
}

/** A `pg` Pool, or anything with the same interface. */
export interface PgPoolLike extends PgQueryable {
	connect(): Promise<PgQueryable & { release(err?: Error | boolean): void }>;
	end(): Promise<void>;
}

/** Options for {@link PostgresLabelStore}. Provide either `pool` or `connectionString`. */
export interface PostgresLabelStoreOptions {
	/**
	 * An existing connection pool to use. The store never ends a pool it was given.
	 */
	pool?: PgPoolLike | undefined;
	/** A PostgreSQL connection string. The store creates and owns its own pool. */
	connectionString?: string | undefined;
	/**
	 * The table to store labels in, optionally schema-qualified (e.g. `labeler.labels`).
	 * The schema and table are created if they don't exist.
	 * @default labels
	 */
	table?: string | undefined;
}

const SCHEMA_IDENTIFIER = /^[a-z_][a-z0-9_]{0,62}$/;
// Table names are capped at 55 characters so the derived "<table>_uri_idx" index name
// fits in Postgres's 63-character identifier limit without being truncated.
const TABLE_IDENTIFIER = /^[a-z_][a-z0-9_]{0,54}$/;

/**
 * Stores labels in a PostgreSQL table.
 *
 * `cts` and `exp` are stored as text, not timestamps: labels are signed over the
 * exact strings, so they must round-trip byte for byte.
 */
export class PostgresLabelStore implements LabelStore {
	/** The connection pool. */
	readonly pool: PgPoolLike;

	/**
	 * The table's schema. If the table name isn't schema-qualified, this is resolved to
	 * the connection's current schema in {@link init}.
	 */
	private schema: string | undefined;

	/**
	 * The quoted table name, safe to interpolate into SQL. Always schema-qualified after
	 * {@link init}, so every connection uses the same table whatever its search_path.
	 */
	private table: string;

	/** The unqualified table name. */
	private readonly tableName: string;

	/**
	 * Key for the advisory lock that orders inserts across processes. Built from the
	 * resolved schema, so "labels" and "public.labels" share a lock.
	 */
	private lockKey = "";

	private readonly ownsPool: boolean;

	constructor(options: PostgresLabelStoreOptions) {
		const parts = (options.table ?? "labels").split(".");
		const tableName = parts[parts.length - 1];
		const schema = parts.length === 2 ? parts[0] : undefined;
		if (
			parts.length > 2 || !TABLE_IDENTIFIER.test(tableName)
			|| (schema !== undefined && !SCHEMA_IDENTIFIER.test(schema))
		) {
			throw new Error(
				`Invalid Postgres table name "${options.table}". Use up to 55 lowercase letters, digits and underscores, optionally prefixed with a schema (e.g. "labeler.labels").`,
			);
		}
		this.tableName = tableName;
		this.schema = schema;
		this.table = parts.map(quoteIdentifier).join(".");

		if (options.pool && options.connectionString) {
			throw new Error("Provide either `pool` or `connectionString` for Postgres, not both.");
		}
		if (options.pool) {
			this.pool = options.pool;
			this.ownsPool = false;
		} else if (options.connectionString) {
			this.pool = new pg.Pool({ connectionString: options.connectionString });
			this.ownsPool = true;
		} else {
			throw new Error("Postgres storage requires either `pool` or `connectionString`.");
		}
	}

	async init() {
		if (this.schema === undefined) {
			const result = await this.pool.query("SELECT current_schema() AS schema");
			const schema = result.rows[0]?.schema;
			if (typeof schema !== "string") {
				throw new Error(
					"Could not determine the Postgres schema for the labels table. Use a schema-qualified table name.",
				);
			}
			this.schema = schema;
		}
		this.table = `${quoteIdentifier(this.schema)}.${quoteIdentifier(this.tableName)}`;
		this.lockKey = `labeler:${this.schema}.${this.tableName}`;

		// CREATE ... IF NOT EXISTS can still fail when two processes run it at once, even for
		// different tables in the same schema, so lock the whole schema while creating things.
		await this.withLock(`labeler-schema:${this.schema}`, (client) => this.createSchema(client));
	}

	private async createSchema(client: PgQueryable) {
		await client.query(`CREATE SCHEMA IF NOT EXISTS ${quoteIdentifier(this.schema!)}`);
		await client.query(`
			CREATE TABLE IF NOT EXISTS ${this.table} (
				id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				src TEXT NOT NULL,
				uri TEXT NOT NULL,
				cid TEXT,
				val TEXT NOT NULL,
				neg BOOLEAN NOT NULL DEFAULT FALSE,
				cts TEXT NOT NULL,
				exp TEXT,
				sig BYTEA
			)
		`);
		// text_pattern_ops lets prefix LIKE queries (uriPatterns ending in *) use the index
		// regardless of the database collation.
		await client.query(
			`CREATE INDEX IF NOT EXISTS "${this.tableName}_uri_idx" ON ${this.table} (uri text_pattern_ops)`,
		);
	}

	async insert(label: SignedLabel) {
		const { src, uri, cid, val, neg, cts, exp, sig } = label;
		// Serialize inserts so ids commit in order. Otherwise a subscriber replaying
		// `id > cursor` could skip a row whose id was assigned earlier but committed later.
		const result = await this.withLock(
			this.lockKey,
			(client) =>
				client.query(
					`INSERT INTO ${this.table} (src, uri, cid, val, neg, cts, exp, sig)
				VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
				RETURNING id`,
					[src, uri, cid || null, val, !!neg, cts, exp || null, sig],
				),
		);
		if (!result.rows.length) throw new Error("Failed to insert label");
		return Number(result.rows[0].id);
	}

	/** Run `fn` in a transaction holding the advisory lock for `key`. */
	private async withLock<T>(key: string, fn: (client: PgQueryable) => Promise<T>): Promise<T> {
		const client = await this.pool.connect();
		try {
			await client.query("BEGIN");
			await client.query("SELECT pg_advisory_xact_lock(hashtext($1))", [key]);
			const result = await fn(client);
			await client.query("COMMIT");
			return result;
		} catch (error) {
			await client.query("ROLLBACK").catch(() => {});
			throw error;
		} finally {
			client.release();
		}
	}

	async query({ uriPatterns, sources, cursor, limit }: LabelQuery) {
		const conditions: string[] = [];
		const values: Array<string | number> = [];
		const param = (value: string | number) => {
			values.push(value);
			return `$${values.length}`;
		};

		if (uriPatterns.length) {
			conditions.push(
				"(" + uriPatterns.map((p) => `uri LIKE ${param(p)} ESCAPE '\\'`).join(" OR ") + ")",
			);
		}
		if (sources.length) {
			conditions.push(`src IN (${sources.map(param).join(", ")})`);
		}
		if (cursor) {
			conditions.push(`id > ${param(cursor)}`);
		}

		const whereClause = conditions.length ? `WHERE ${conditions.join(" AND ")}` : "";
		const result = await this.pool.query(
			`SELECT * FROM ${this.table} ${whereClause} ORDER BY id ASC LIMIT ${param(limit)}`,
			values,
		);
		return result.rows.map(rowToLabel);
	}

	async maxId() {
		const result = await this.pool.query(`SELECT MAX(id) AS id FROM ${this.table}`);
		return Number(result.rows[0]?.id ?? 0);
	}

	async ping() {
		await this.pool.query("SELECT 1");
	}

	async close() {
		if (this.ownsPool) await this.pool.end();
	}
}

/** Quote a Postgres identifier, escaping any embedded double quotes. */
function quoteIdentifier(name: string) {
	return `"${name.replaceAll("\"", "\"\"")}"`;
}

function rowToLabel(row: Record<string, unknown>): StoredLabel {
	if (!row.sig) throw new Error(`Label ${String(row.id)} has no signature`);
	return {
		id: Number(row.id),
		src: row.src as Did,
		uri: row.uri as string,
		val: row.val as string,
		neg: Boolean(row.neg),
		cts: row.cts as Datetime,
		...(row.cid ? { cid: row.cid as string } : {}),
		...(row.exp ? { exp: row.exp as Datetime } : {}),
		sig: new Uint8Array(row.sig as Uint8Array),
	};
}
